### ISSUE TITLE
누락된 피드백 

### ISSUE THREAD

**Issue by GangWoon** [Jinsujin/issue-tracker#30]
- Protocol, Struct closure abstraction이 명확한 기준이 없이 동시에 사용되고 있다는 느낌을 받았습니다.
특정 부분은 Delegate 패턴을 사용하시며, 다른 부분에선 Environment라는 객체를 통해서 추상화하고 계십니다. 해당 부분에 있어서 컨셉을 명확하게 유지하셨으면 좋겠습니다.

- Time Sequence Design 
![HappyBirthdayEdit](https://user-images.githubusercontent.com/48466830/188258421-eac11596-0276-49db-9785-96641034a835.png)

같이 보지 못했던 질문들은 코맨트를 달아주시거나,  PR 요청하시면 확인하도록 하겠습니다.

**Comment by bibi6666667** [comment]
넵 꼼꼼히 봐주셔서 감사합니다! 우선 이슈목록 갱신 관련해서 수정한 코드와 누락된 질문을 묶어서 새 PR로 올리도록 하겠습니다. 🙇‍♀️
